insert into  jenkins_user(id , nombre) values(1, 'Raul');
insert into  jenkins_user(id , nombre) values(2, 'Maco');
insert into  jenkins_user(id , nombre) values(3, 'Mario');
insert into  jenkins_user(id , nombre) values(4, 'Jorge');
insert into  jenkins_user(id , nombre) values(5, 'Carlos');
insert into  jenkins_user(id , nombre) values(6, 'Erick');
insert into  jenkins_user(id , nombre) values(7, 'Mariano');
insert into  jenkins_user(id , nombre) values(8, 'Manolo');
insert into  jenkins_user(id , nombre) values(9, 'Manuel');
insert into  jenkins_user(id , nombre) values(10, 'Julio');
insert into  jenkins_user(id , nombre) values(11, 'Requena');
insert into  jenkins_user(id , nombre) values(12, 'Mariela');
insert into  jenkins_user(id , nombre) values(13, 'Viviana');
insert into  jenkins_user(id , nombre) values(14, 'Carla');
insert into  jenkins_user(id , nombre) values(15, 'Nancy');
insert into  jenkins_user(id , nombre) values(16, 'Maria');
insert into  jenkins_user(id , nombre) values(17, 'Jimena');
insert into  jenkins_user(id , nombre) values(18, 'Raquel');
insert into  jenkins_user(id , nombre) values(1, 'Raul');
insert into  jenkins_user(id , nombre) values(2, 'Maco');
insert into  jenkins_user(id , nombre) values(3, 'Mario');
insert into  jenkins_user(id , nombre) values(4, 'Jorge');
insert into  jenkins_user(id , nombre) values(5, 'Carlos');
insert into  jenkins_user(id , nombre) values(6, 'Erick');
insert into  jenkins_user(id , nombre) values(7, 'Mariano');
insert into  jenkins_user(id , nombre) values(8, 'Manolo');
insert into  jenkins_user(id , nombre) values(9, 'Manuel');
insert into  jenkins_user(id , nombre) values(10, 'Julio');
insert into  jenkins_user(id , nombre) values(11, 'Requena');
insert into  jenkins_user(id , nombre) values(12, 'Mariela');
insert into  jenkins_user(id , nombre) values(13, 'Viviana');
insert into  jenkins_user(id , nombre) values(14, 'Carla');
insert into  jenkins_user(id , nombre) values(15, 'Nancy');
insert into  jenkins_user(id , nombre) values(16, 'Maria');
insert into  jenkins_user(id , nombre) values(17, 'Jimena');
insert into  jenkins_user(id , nombre) values(18, 'Raquel');

insert into  jenkins_Proveedores(id , nombre) values(1, 'Raul');
insert into  jenkins_Proveedores(id , nombre) values(2, 'Maco');
insert into  jenkins_Proveedores(id , nombre) values(3, 'Mario');
insert into  jenkins_Proveedores(id , nombre) values(4, 'Jorge');
insert into  jenkins_Proveedores(id , nombre) values(5, 'Carlos');
insert into  jenkins_Proveedores(id , nombre) values(6, 'Erick');
insert into  jenkins_Proveedores(id , nombre) values(7, 'Mariano');
insert into  jenkins_Proveedores(id , nombre) values(8, 'Manolo');
insert into  jenkins_Proveedores(id , nombre) values(9, 'Manuel');
insert into  jenkins_Proveedores(id , nombre) values(10, 'Julio');
insert into  jenkins_Proveedores(id , nombre) values(11, 'Requena');
insert into  jenkins_Proveedores(id , nombre) values(12, 'Mariela');
insert into  jenkins_Proveedores(id , nombre) values(13, 'Viviana');
insert into  jenkins_Proveedores(id , nombre) values(14, 'Carla');
insert into  jenkins_Proveedores(id , nombre) values(15, 'Nancy');
insert into  jenkins_Proveedores(id , nombre) values(16, 'Maria');
insert into  jenkins_Proveedores(id , nombre) values(17, 'Jimena');
insert into  jenkins_Proveedores(id , nombre) values(18, 'Raquel');
insert into  jenkins_Proveedores(id , nombre) values(1, 'Raul');
insert into  jenkins_Proveedores(id , nombre) values(2, 'Maco');
insert into  jenkins_Proveedores(id , nombre) values(3, 'Mario');
insert into  jenkins_Proveedores(id , nombre) values(4, 'Jorge');
insert into  jenkins_Proveedores(id , nombre) values(5, 'Carlos');
insert into  jenkins_Proveedores(id , nombre) values(6, 'Erick');
insert into  jenkins_Proveedores(id , nombre) values(7, 'Mariano');
insert into  jenkins_Proveedores(id , nombre) values(8, 'Manolo');
insert into  jenkins_Proveedores(id , nombre) values(9, 'Manuel');
insert into  jenkins_Proveedores(id , nombre) values(10, 'Julio');
insert into  jenkins_Proveedores(id , nombre) values(11, 'Requena');
insert into  jenkins_Proveedores(id , nombre) values(12, 'Mariela');
insert into  jenkins_Proveedores(id , nombre) values(13, 'Viviana');
insert into  jenkins_Proveedores(id , nombre) values(14, 'Carla');
insert into  jenkins_Proveedores(id , nombre) values(15, 'Nancy');
insert into  jenkins_Proveedores(id , nombre) values(16, 'Maria');
insert into  jenkins_Proveedores(id , nombre) values(17, 'Jimena');
insert into  jenkins_Proveedores(id , nombre) values(18, 'Raquel');


insert into  jenkins_Tiendas(id , nombre) values(1, 'Plaza Alamos');
insert into  jenkins_Tiendas(id , nombre) values(2, 'Miraflores');
insert into  jenkins_Tiendas(id , nombre) values(3, 'El Naranjo');
insert into  jenkins_Tiendas(id , nombre) values(4, 'Plaza Madero');
insert into  jenkins_Tiendas(id , nombre) values(5, 'SanCris');
insert into  jenkins_Tiendas(id , nombre) values(6, 'Mix');
insert into  jenkins_Tiendas(id , nombre) values(7, 'Proceres');


